# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amabooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/img'),
        ),
    ]
